version: '3.8'

services:
  app:
    build: .
    working_dir: /app/app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./data:/app/app/data
    environment:
      - ENV=production
    command: sh -c "python populate_db.py && uvicorn main:app --host 0.0.0.0 --port 8000"
